# Generated by Django 6.0.3 on 2026-03-15 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_duration', models.DurationField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.IntegerField()),
                ('status', models.CharField(choices=[('normal', 'Binh thuong'), ('cavity', 'Sau rang'), ('crown', 'Rang su'), ('missing', 'Mat rang'), ('treated', 'Da dieu tri')], default='normal', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teeth', to='patients.patient')),
            ],
            options={
                'ordering': ['patient', 'tooth_number'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('resulting_tooth_status', models.CharField(choices=[('normal', 'Binh thuong'), ('cavity', 'Sau rang'), ('crown', 'Rang su'), ('missing', 'Mat rang'), ('treated', 'Da dieu tri')], default='treated', help_text='Trang thai se duoc cap nhat cho cac rang khi hoan tat lieu trinh.', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plan', to='scheduling.appointment')),
                ('services', models.ManyToManyField(blank=True, related_name='treatment_plans', to='clinical.service')),
                ('teeth', models.ManyToManyField(blank=True, related_name='treatment_plans', to='clinical.tooth')),
            ],
            options={
                'ordering': ['-appointment__date', '-appointment__time_slot'],
            },
        ),
        migrations.AddConstraint(
            model_name='tooth',
            constraint=models.UniqueConstraint(fields=('patient', 'tooth_number'), name='uniq_patient_tooth'),
        ),
        migrations.AddConstraint(
            model_name='tooth',
            constraint=models.CheckConstraint(condition=models.Q(('tooth_number__gte', 11), ('tooth_number__lte', 48)), name='tooth_number_between_11_48'),
        ),
    ]
