# Generated by Django 6.0.3 on 2026-05-28 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tooth',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_teeth', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tooth',
            name='status',
            field=models.CharField(choices=[('normal', 'Bình thường'), ('cavity', 'Sâu răng'), ('crown', 'Răng sứ'), ('missing', 'Mất răng'), ('treated', 'Đã điều trị')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='resulting_tooth_status',
            field=models.CharField(choices=[('normal', 'Bình thường'), ('cavity', 'Sâu răng'), ('crown', 'Răng sứ'), ('missing', 'Mất răng'), ('treated', 'Đã điều trị')], default='treated', help_text='Trạng thái sẽ được cập nhật cho các răng khi hoàn tất liệu trình.', max_length=20),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='status',
            field=models.CharField(choices=[('planned', 'Đã lên kế hoạch'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn tất')], default='planned', max_length=20),
        ),
    ]
